language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted

install:
  - luarocks make rockspecs/aad-0.1.0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared"

script:
  - cd corona-app
  - busted

# after_success:
#   - coveralls -b .. -r .. -i ./src --dump c.report.json
#   - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
